swagger: "2.0"
info:
  description: Servicio para llamar al servicio ExtendedStatusflow de Omnistore
  version: 1.0.0
  title: extended_status_flow_v1
schemes:
 - http
produces:
 - application/json
security:
 -
  default: []
paths:
  /:
    get:
      tags:
       - extended-status-flow
      description: |-
        Servicio de consulta del extended-status-flow.  Puede recibir identificadores de producto, refrencia. También es obligatorio que reciba el **siteId** cuyos valores pueden ser
        - eciStore
        - ltcStore
        - portugalStore
        - ukStore
        - franceStore
        - hipercorStore
      parameters:
       -
        name: siteId
        in: query
        description: Identificador del sitio
        required: true
        type: string
       -
        name: references
        in: query
        description: Referencias de las que queremos saber stock y precios
        required: false
        type: string
       -
        name: products
        in: query
        description: Identificadores de productos de los que queremos saber statusflow
        required: false
        type: string
       -
        name: skus
        in: query
        description: Identificadores de skus de los que queremos saber statusflow
        required: false
        type: string
       -
        name: locale
        in: query
        description: Locale
        required: false
        type: string
       -
        name: eciExpressCentreId
        in: query
        description: ExpressCentreId
        required: false
        type: string
       -
        name: giftSkus
        in: query
        description: GiftSkus
        required: false
        type: string
       -
        name: originRequest
        in: query
        description: OriginRequest
        required: false
        type: string
       -
        name: fromFirefly
        in: query
        description: FromFirefly
        required: false
        type: string
      responses:
        "200":
          description: Ok la llamada es correcta.
          schema:
            $ref: '#/definitions/products'
        "400":
          description: La llamada no es correcta.
          schema:
            $ref: '#/definitions/errors'
        "500":
          description: La llamada no es correcta.
          schema:
            $ref: '#/definitions/errors'
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
securityDefinitions:
  default:
    type: oauth2
    authorizationUrl: https://test.com
    flow: implicit
definitions:
  products:
    type: array
    description: Items con precios y stock
    items:
      type: object
      properties:
        offer_shipping_details:
          type: array
          description: Métodos de envío posibles y gastos de envío.
          items:
            $ref: '#/definitions/offer_shipping_detail'
        product:
          $ref: '#/definitions/product'
  offer_shipping_detail:
    type: object
    properties:
      identifier:
        type: integer
        description: Identificador del shipping para ser usado dentro de un product/sku/offer
      delivery_time:
        type: string
        description: Fecha de compromiso
      stock:
        type: string
        description: Información de entrega en 48 horas.
        enum:
         - E24
         - S24
         - S48
         - vS72
         - S10
         - "NO"
         - S10_DOC
         - S30
         - S14
         - S6
         - E48
         - V05
         - V48
         - D48
         - E72
         - D72
      delivery_methods:
        type: array
        description: "Destinos a donde esta permitido, HomeDelivery ECIExpress (antes era Domicilio y flag express_checkout, true  SUPERCOR CORREOS"
        items:
          $ref: '#/definitions/delivery_method'
      ineligible_regions:
        type: array
        description: Paises a donde NO está permitido
        items:
          type: string
      product_return_policy:
        $ref: '#/definitions/product_return_policy'
      delivery_type_badges:
        $ref: '#/definitions/delivery_types'
      item_availability:
        type: string
        description: Si se puede añadir a la cesta o no.
        enum:
         - ADD
         - SOLD_OUT
         - RESERVE
         - NOT_AVAILABLE
         - FORM
         - CC_ONLY
         - ONLY_CLICK_AND_EXPRESS
         - NO_SALE
         - ONLY_CENTRES
         - TEMPORARY_UNAVAILABLE
  product:
    type: object
    properties:
      product_id:
        type: string
        description: Identificador de producto.
      description:
        type: string
        description: Título del producto.
      categories:
        type: array
        description: Categorías padres. Si son las mismas para todas las variantes vendrán informadas a este nivel.
        items:
          $ref: '#/definitions/category'
      related_services:
        type: array
        description: Señales de servicio.
        items:
          $ref: '#/definitions/signal_services'
      is_mandatory:
        type: boolean
        description: Tiene Señales de servicio obligatorias.
      is_searchable:
        type: boolean
        description: Si es un producto buscable
      product_variants:
        type: array
        description: Información de las variantes del producto.
        items:
          $ref: '#/definitions/product_variant'
      digital_store:
        type: string
        description: Id de tienda.
      offer_shipping_detail:
        $ref: '#/definitions/offer_shipping_detail'
  product_variant:
    type: object
    properties:
      media_objects:
        type: array
        description: Información de multimedia puede haber imágenes videos o audios.
        items:
          $ref: '#/definitions/multimedia'
      gtin:
        type: string
        description: GTIN (ean)
      identifier:
        type: string
        description: Código externo PIM de WPC. Id acabado en 001.
      offers:
        type: array
        description: The Stock Keeping Units.
        items:
          $ref: '#/definitions/sku'
  category:
    type: object
    properties:
      identifier:
        type: string
        description: Id de la categoría
  promotional_action:
    type: object
    properties:
      identifier:
        type: string
        description: Identificador de la promoción para ser linkado desde el sku.
      name:
        type: string
        description: Nombre de la promo
      is_corporate:
        type: boolean
        description: Indica si la promo es corporativa
      is_exclusive:
        type: boolean
        description: Indica si la promo es excluyente. Por ej si una promo al coste es compatible con otra.
      is_mandatory:
        type: boolean
        description: Flag de promociones al coste que indica si es el servicio es obligatorio.
      description:
        type: string
        description: Description
      start_date:
        type: string
        description: Día inicio de la promo.
      end_date:
        type: string
        description: Fecha fin de la promo.
      type:
        type: string
        description: Tipo de la promo shipping informativa coste.
      url:
        type: string
        description: Url de la promo.
  seller:
    type: object
    properties:
      identifier:
        type: string
        description: Identificador del vendedor.
  signal_services:
    type: object
    properties:
      name:
        type: string
        description: Nombre de la señal de servicio.
      type:
        type: string
        description: Tipo de la señal de servicio.
      mode:
        type: string
        description: Código.
      url:
        type: string
        description: URL del popup de aceptar condiciones (como por ejemplo en aires acondicionados).
      service_detail:
        $ref: '#/definitions/installation'
  multimedia:
    type: object
    properties:
      url:
        type: string
        description: Url de la imagen.
      ratio:
        type: number
        description: Información del ratio.
      media_type:
        type: string
        description: "Tipo de objeto multimedia, audio image video document."
        enum:
         - AUDIO
         - IMAGE
         - VIDEO
         - DOCUMENT
      size:
        type: string
        description: Tamaño del objeto multimedia.
        enum:
         - SMALL MEDIUM BIG ZOOM SQUARE VERTICAL
  identifier_name:
    type: object
    properties:
      identifier:
        type: string
        description: Id de la marca.
      name:
        type: string
        description: Nombre de la marca.
    description: Empresas STS donde se permite recoger el producto.
  region:
    type: object
    properties:
      name:
        type: string
        description: "Por ejemplo, España peninsular."
      shipping_rate:
        type: string
        description: Gastos de envío / devolución.
  delivery_method:
    type: object
    properties:
      name:
        type: string
        description: "Por ejemplo, Home Delivery OpenCor CORREOS Supercor ECI Express..."
      defined_regions:
        type: array
        description: Regiones de este shipping method. Vienen por orden de prioridad.
        items:
          $ref: '#/definitions/region'
  product_return_policy:
    type: object
    properties:
      description:
        type: array
        description: Información de la devolución.
        items:
          type: string
    description: Información de la devolución.
  sku:
    type: object
    properties:
      seller:
        $ref: '#/definitions/seller'
      sales_reference:
        type: string
        description: Referencia ECI.
      stock_amount:
        type: integer
        description: Stock.
      item_availability:
        type: string
        description: Si se puede añadir a la cesta o no.
        enum:
         - ADD
         - SOLD_OUT
         - RESERVE
         - NOT_AVAILABLE
         - FORM
         - CC_ONLY
         - ONLY_CLICK_AND_EXPRESS
         - NO_SALE
         - ONLY_CENTRES
         - TEMPORARY_UNAVAILABLE
      price_specification:
        $ref: '#/definitions/price_specification'
      offer_shipping_detail:
        $ref: '#/definitions/offer_shipping_detail'
      related_services:
        type: array
        description: Señales de servicio. Si son las mismas promociones con instalación para ofertas MKP y ECI se puede rellenar a nivel de producto (colchones mamparas de ducha sofas).
        items:
          $ref: '#/definitions/signal_services'
  installation:
    type: object
    properties:
      promotional_action:
        $ref: '#/definitions/promotional_action'
      product:
        $ref: '#/definitions/product'
    description: Si el servicio es de tipo INSTALLATION significa que tiene promoción al coste asociada. Esta es la info de la promoción al coste y producto asociado.
  delivery_types:
    type: object
    properties:
      is_home_delivery:
        type: boolean
        description: Si admite home_delivery.
      is_sts_pickup:
        type: boolean
        description: Si admite entrega en STS (Opencor Correos...)
      is_eci_pickup:
        type: boolean
        description: Si admite recogida en centro ECI.
      is_eci_express:
        type: boolean
        description: Si admite recogida en centro ECI.
      is_click_and_car:
        type: boolean
        description: Si admite click and car.
      sts_companies:
        $ref: '#/definitions/identifier_name'
    description: Flags e info de shipping methods disponibles.
  price_specification:
    type: object
    properties:
      price:
        type: string
        description: Price.
      sale_price:
        type: string
        description: Precio con descuento.
      discount_percentage:
        type: number
        description: Descuento entre price y sale_price.
    description: Price.
  errors:
    type: array
    items:
      type: object
      properties:
        description:
          type: string
        code:
          type: string
x-throttling-tier: 250KPerMin
x-wso2-cors:
  corsConfigurationEnabled: true
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - http://apiecommerce.eci.geci:12585/ecommerce/extended-status-flow
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - http://apiecommerce.eci.geci:12585/ecommerce/extended-status-flow
  type: http
x-wso2-basePath: /products/extended-status-flow/v1/1.0.0
x-wso2-transports:
 - http
 - https
x-wso2-application-security:
  security-types:
   - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
